### ISSUE TITLE
Vitamins 

### ISSUE THREAD

**Issue by davidguerreiro** [davidguerreiro/evscalculator#7]
We also need to include vitamins. I forget about that !!

Please read step three of this article carefully to understand what I'm talking about: http://www.smogon.com/forums/threads/beginning-guide-to-ev-training-in-oras-xy.3550097/

We could include vitamins button in the same way we are including the hordes pokemon in the second screen. There are some limitations about the use of the vitamins so it's really important to talk about this on our next meeting.

**Comment by jaicab** [comment]
Fine, so there's another scenario. Let's break it down:

**Vitamines**
- Add 10 EVs to a stat.
- Only work when stat < 100 EVs.
- They are to be used at the start, because when > 100 they don't work.

The question is, what are the odds of actually having any vitamins? Would people buy vitamins before using hordes? Is it faster to get the vitamins than fighting agains the hordes? Depending on how important this is we should give it more or less importance.

**Comment by davidguerreiro** [comment]
Well, I have never used them, but I know that some expert players use vitamins in some point of the training,.. They are quite expensive, though. It is explained in the article above. Anyway, I think that we should include them and then see if the users use vitamins or not.

**Comment by jaicab** [comment]
Ok, so this should go into #3. I'm going to move the content and close this.
